### ISSUE TITLE
Line 148-150: This example highly depends on the gain variance assumed. The gain variance assumed here (25%) is quite small compared to most real PMTs.

### ISSUE THREAD

**Issue by heroxbd** [heroxbd/waveform-analysis#102]

**Comment by heroxbd** [comment]
related to https://github.com/heroxbd/waveform-analysis/issues/99

**Comment by dachengx** [comment]
Addressed in e9383d5613168161f9746ac2dbdc1d76c12bbb3a

**Comment by dachengx** [comment]
> Line 148-150: This example highly depends on the gain variance assumed. The gain variance assumed here (25%) is quite small compared to most real PMTs. 

We change the variance of gain from 0.25 to 0.4 to match prevalent PMTs. Though the performance of waveform analysis methods depends on the variance we choose, a larger gain spread leads to a larger chance to misidentify PE numbers, which further justifies our argument here.

**Comment by dachengx** [comment]
NEED literature about gain variance.

**Comment by dachengx** [comment]
Close with: https://gitlab.airelinux.org/tjjk/publication/-/issues/9#note_5115
