### ISSUE TITLE
Line 185-186: waveform shifting: This is extremely confusing. What was actually done for this calculation ? What is the method. What waveform is being shifted ? What is ∆t ? How is it chosen according to single PE ?

### ISSUE THREAD

**Issue by heroxbd** [heroxbd/waveform-analysis#105]

**Comment by heroxbd** [comment]
调研一下中微子领域使用的 sum of waveform 方法。我记得的例子有 https://journals.aps.org/prd/abstract/10.1103/PhysRevD.92.052006 应该还有很多，再找两个例子，用来佐证我们拿 waveform shifting 来比较的意义。

**Comment by littlewu2508** [comment]
[KamLAND](https://journals.aps.org/prd/abstract/10.1103/PhysRevD.92.052006) 引文[11]：LENA 中质子衰变的 proposal 已经上传 zotero。该 proposal 没有有关波形的内容

**Comment by littlewu2508** [comment]
经过一些调查发现了 1 篇使用波形形状做后续分析的文章。

Pulse shape particle identification by a single large hemispherical photomultiplier tube

此文试图做 PID，提取了波形的展宽作为 discriminator

--

**Comment by heroxbd** [comment]
littlewu2508 ***@***.***> writes:

> 经过一些调查发现了 1 篇使用波形形状做后续分析的文章。
>
> Pulse shape particle identification by a single large hemispherical photomultiplier tube
>
> 此文试图做 PID，提取了波形的展宽作为 discriminator

这里的实验设定是粒子能量特别高，从而 PE 都叠在一起，只能通过波形展宽做研
究。

与我们论文的逻辑相符：PE 彻底没分开，PE 的时间信息完全被 SPE pulse 模糊
掉。此时时间精度最差。

可以做为我们讨论 waveform shifting （取个更恰当的名字）的依据

**Comment by heroxbd** [comment]
给出 waveform shifting 和 peaking finding 的严格定义

**Comment by heroxbd** [comment]
还需要给出 waveform shifting 的表达式和 alpha scaling 的定义。
