### ISSUE TITLE
Section 3.3: This section introduction is thoroughly too brief and unhelpful. Deconvolution is known to be unreliable due to poor conditioning of the data. How is that handled for real analysis of data ?

### ISSUE THREAD

**Issue by heroxbd** [heroxbd/waveform-analysis#107]

**Comment by heroxbd** [comment]
爱强，调研一下用了退卷积方法的组，至少 JUNO 是这样的。Borexino 好像也做了。至少找三个例子佐证我们为什么要考虑退卷积法。

**Comment by greatofdream** [comment]
Borexino 以前的电子学似乎不能记录波形 https://borex.lngs.infn.it/Thesis/J.Q.Meindl_PhD_Thesis.pdf 3.2.2节说电子学会积分脉冲后的前80ns 并记录起始时间，感觉类似于juno的小pmt(The Borexino detector at the Laboratori Nazionali del Gran Sasso)；在后来的分析(https://journals.aps.org/prd/pdf/10.1103/PhysRevD.101.012009)提到了波形，但是没有看到有波形分析

**Comment by greatofdream** [comment]
Deconvolution method is still used in many experiments, for example DayaBay[1] and JUNO protontype[2]. Due to deconvolution is a well-developed and widely used technique in Digital Signal Processing[1], and is fast via FFT algorithm.
[1] Yongbo Huang(2018).The Flash ADC system and PMT waveform reconstruction for the Daya Bay Experiment
[2] H.Q. Zhang(2019).Comparison on PMT waveform reconstructions with JUNO prototype.

**Comment by greatofdream** [comment]
> 

这里面连没有波形分析啊

**Comment by heroxbd** [comment]
> Borexino 以前的电子学似乎不能记录波形 https://borex.lngs.infn.it/Thesis/J.Q.Meindl_PhD_Thesis.pdf 3.2.2节说电子学会积分脉冲后的前80ns 并记录起始时间，感觉类似于juno的小pmt(The Borexino detector at the Laboratori Nazionali del Gran Sasso)；在后来的分析([https://journals.aps.org/prd/pdf/10.1103/PhysRevD.101.012009)提到了波形，但是没有看到有波形分析](https://journals.aps.org/prd/pdf/10.1103/PhysRevD.101.012009)%E6%8F%90%E5%88%B0%E4%BA%86%E6%B3%A2%E5%BD%A2%EF%BC%8C%E4%BD%86%E6%98%AF%E6%B2%A1%E6%9C%89%E7%9C%8B%E5%88%B0%E6%9C%89%E6%B3%A2%E5%BD%A2%E5%88%86%E6%9E%90)

see https://gitlab.airelinux.org/tjjk/publication/-/issues/10

**Comment by greatofdream** [comment]
我怀疑Borexino的波形分析并没有放到官方的论文里，仅在[这里第7节](https://journals.aps.org/prd/pdf/10.1103/PhysRevD.101.012009)有一点迹象说使用了FADC波形做多种深度学习分析，但是没有看到反卷积方式

**Comment by heroxbd** [comment]
> 我怀疑Borexino的波形分析并没有放到官方的论文里，仅在[这里第7节](https://journals.aps.org/prd/pdf/10.1103/PhysRevD.101.012009)有一点迹象说使用了FADC波形做多种深度学习分析进行muon tag，但是没有看到反卷积方式

Borexino 的作者们对应于 zotero 中的 Charge reconstruction in large-area photomultipliers

**Comment by heroxbd** [comment]
他们用的反卷积技术
