### ISSUE TITLE
Figure 8: This uses language that is probably unfamiliar to the readers of JINST. What is a "hinge" and what are "whiskers" ? We do not do 25% and 75% confidence intervals usually. 

### ISSUE THREAD

**Issue by heroxbd** [heroxbd/waveform-analysis#114]

**Comment by heroxbd** [comment]
换成 1sigma 对应的分位数的 error-bar 试试

**Comment by dachengx** [comment]
Using boxplots is a confusing way. We change the "hinge" and what are "whiskers" to the quantile of Gaussian distribution's positive and negative standard deviation, which are 15.8% and 84.1%. This errorbar setting is widely used in describing non-Gaussian distribution.

**Comment by heroxbd** [comment]
好的，那把原文也一起改一下
