### ISSUE TITLE
Eq. 3.17: As remarked earlier, the assumption of a normal distribution for the charge gain is wrong. And it creates a problem for the model since with a normal distribution the charge can be negative which is unphysical.

### ISSUE THREAD

**Issue by heroxbd** [heroxbd/waveform-analysis#118]

**Comment by heroxbd** [comment]
Related to https://github.com/heroxbd/waveform-analysis/issues/99

**Comment by dachengx** [comment]
Addressed in e9383d5613168161f9746ac2dbdc1d76c12bbb3a

**Comment by dachengx** [comment]
Gaussian is not the best model to describe the charge distribution, especially when the variance is large. We change the Gaussian to Gamma distribution to avoid unphysical negative charges. The analysis methods are mostly not affected.

**Comment by dachengx** [comment]
NEED literature about charge distribution. NEED justification on Gaussian assumption in FSMP.

**Comment by heroxbd** [comment]
Eq 3.17 是 MCMC 法，把里边的 Gaussian 改成 Gamma 再跑一遍。

**Comment by dachengx** [comment]
> Eq 3.17 是 MCMC 法，把里边的 Gaussian 改成 Gamma 再跑一遍。

已经跑完了

**Comment by heroxbd** [comment]
> > Eq 3.17 是 MCMC 法，把里边的 Gaussian 改成 Gamma 再跑一遍。
> 
> 已经跑完了

好的，更新了图之后 close 本 issue
