### ISSUE TITLE
把 t_ALL 和 t_1st 比较图分成两个子图

### ISSUE THREAD

**Issue by heroxbd** [heroxbd/waveform-analysis#145]
方便正文中分别引用

**Comment by dachengx** [comment]
![image](https://user-images.githubusercontent.com/40532474/165670661-6f779dcb-4371-497b-9487-722c7105b147.png)

左图拆分成两个，右图删除？

**Comment by heroxbd** [comment]
> ![image](https://user-images.githubusercontent.com/40532474/165670661-6f779dcb-4371-497b-9487-722c7105b147.png)
> 
> 左图拆分成两个，右图删除？

No。把一个文件，拆分成其它 figure 那样的 (a) (b) 两个小文件，(a) 不带 legend，(b) 带 legend。
