### ISSUE TITLE
Note/figures/profile.pgf 上加一个 t_0 和 mu 影响的示意

### ISSUE THREAD

**Issue by heroxbd** [heroxbd/waveform-analysis#146]
指示 light curve 左右移动由 t_0 控制，上下伸缩由 mu 控制。可以直接写 tikz 在 pgf 上编辑吗？

**Comment by dachengx** [comment]
直接加几个箭头？

**Comment by dachengx** [comment]
![image](https://user-images.githubusercontent.com/40532474/165674983-2a0b7031-54b8-4ae7-97be-ef8fcff83426.png)

**Comment by heroxbd** [comment]
行！画成双箭头，表示可以左右移动和上下缩放
