### ISSUE TITLE
CNN might lose its self-regulared sparsity

### ISSUE THREAD

**Issue by dachengx** [heroxbd/waveform-analysis#152]
https://github.com/heroxbd/waveform-analysis/blob/master/Note/Discussion.tex#L41

**Comment by heroxbd** [comment]
啥意思，与 section 3 矛盾吗？

**Comment by dachengx** [comment]
<img width="945" alt="image" src="https://user-images.githubusercontent.com/40532474/165742768-dfe66c0c-ad86-4c2b-b78b-0c3d48d4afcd.png">

看起来不明显了

**Comment by heroxbd** [comment]
Close?
