### ISSUE TITLE
Proof of publication

### ISSUE THREAD

**Issue by heroxbd** [heroxbd/waveform-analysis#162]
[JINST_063P_1221.pdf](https://github.com/heroxbd/waveform-analysis/files/8948978/JINST_063P_1221.pdf)

In particular, please reply to the typesetter's queries on the first
page of the paper (without your reply the article cannot be
published).

Our typesetting procedure is based on the preparation of a "new version" of
the original .tex file, which reflects the journal’s style. This new .tex
file may be very different from the original one, thus the best way to
submit your correction requests is to make a list of the changes you would
like to be implemented in the final version of the paper, for instance:

1 - On page 3, line 10, please change "this" to "that"
2 - ...

If you need to modify large pieces of text, or entire equations, snippets
of LaTeX code are welcome.

**Comment by TakaraJikin** [comment]
2. In JINST affiliations are written in the form:
Department, University,
Street, City, Country
Please check each affiliation and provide the missing information if needed.

我们需要提供更具体的地址信息吗？例如什么区邮政编码？

**Comment by heroxbd** [comment]
Takara Jikin ***@***.***> writes:

> 2 In JINST affiliations are written in the form:
>  Department, University,
>  Street, City, Country
>  Please check each affiliation and provide the missing information if needed.
>
> 我们需要提供更具体的地址信息吗？例如什么区邮政编码？

我觉得不需要，现在的形式就够了。因为当今寄信已经不那么重要了。

**Comment by littlewu2508** [comment]
Page 2, Line 5:  experiments undergoes to development ->  experiments undergoes development? 感觉 undergoes to 没见过 
--

**Comment by littlewu2508** [comment]
Page 5, Line 13-14: To better model the rising edge curvature than Hamilton -> To model the rising edge curvature better than Hamilton

**Comment by dachengx** [comment]
Page 2, fourth-to-last line: the proximity of them -> their proximity

**Comment by dachengx** [comment]
Page 3, Line 1: intercorelated -> intercorrelated

**Comment by littlewu2508** [comment]
公式 (2.7) 不严格，容易给人 \epsilon(t) 加了 N_PE 次的错觉

**Comment by dachengx** [comment]
Page 4, Line 4: extra -> the extra

**Comment by dachengx** [comment]
Page 5, Line 19: reasonable -> a reasonable

**Comment by dachengx** [comment]
Page 5, Line 19: underlying -> the underlying

**Comment by dachengx** [comment]
Page 5, Line 4: translate -> translates

**Comment by littlewu2508** [comment]
Page 8, section 3, line 2: `from 1 to $\hat{N}_\mathrm{PE}$ and $\hat{N}_\mathrm{PE}$ is an estimator of $N_\mathrm{PE}$ in eq.~\eqref{eq:lc-sample}` -> `from 1 to $\hat{N}_\mathrm{PE}$, an estimator of $N_\mathrm{PE}$ in eq.~\eqref{eq:lc-sample}.
-- `

**Comment by dachengx** [comment]
Page 6, fifth-to-last line: substantial -> a substantial

**Comment by dachengx** [comment]
Page 8, Line 1: Resolution -> The resolution

**Comment by dachengx** [comment]
Page 9, Line 3: MLE like -> MLE-like

**Comment by dachengx** [comment]
Page 9, fourth-to-last line: remain -> remains

**Comment by dachengx** [comment]
Page 11, Line 5: extracts -> extract

**Comment by dachengx** [comment]
Page 11, Line 9: shift -> and shift

**Comment by dachengx** [comment]
Page 11, Line 9: a SER -> an SER

**Comment by dachengx** [comment]
Page 11, sixth-to-last line: but found -> but is found

**Comment by dachengx** [comment]
Page 14, Line 6: an 1 dimensional -> a 1-dimensional

**Comment by dachengx** [comment]
Page 14, Line 7: 1 dimensional -> 1-dimensional

**Comment by dachengx** [comment]
Page 14, fourth-to-last line: one-channelled -> 1-channel

**Comment by littlewu2508** [comment]
s/convoluted/convoled/g

convoluted 是晦涩难懂的（被卷了很多次的）

**Comment by dachengx** [comment]
Page 19, Line 2: Metropolis-Hasings -> Metropolis-Hastings

**Comment by littlewu2508** [comment]
Page 9, line 6 from bottom: RSS will -> RSS would

**Comment by dachengx** [comment]
Page 23, Line 4: As figure -> In figure

**Comment by dachengx** [comment]
Reference 我没查出问题

**Comment by heroxbd** [comment]
> Page 2, Line 5: experiments undergoes to development -> experiments undergoes development? 感觉 undergoes to 没见过 --

应该是 to -> two

**Comment by heroxbd** [comment]
@dachengx 确认一下 Figure 6(b) 的 LucyDDM D_w = 0.60ns 是否正确。它比 CNN 和 Fitting 都小。

**Comment by littlewu2508** [comment]
Page 14, line 8:  fixed sample size $N_s$ 后面加逗号

**Comment by littlewu2508** [comment]
> one

是 a 1-channeld 还是 an 1-channeled?

**Comment by Berrysoft** [comment]
> > one
> 
> 是 a 1-channeld 还是 an 1-channeled?

a, /wan/

**Comment by littlewu2508** [comment]
Page 18, right below figure 10, "= 1, The" T lowercase

**Comment by dachengx** [comment]
> @dachengx 确认一下 Figure 6(b) 的 LucyDDM D_w = 0.60ns 是否正确。它比 CNN 和 Fitting 都小。

确认没有问题

**Comment by littlewu2508** [comment]
section 3.5.3, marginalizing out q 0 and z gives a flattened model -> marginalizing out q 0 and z, we arrives at a flattened model,

**Comment by littlewu2508** [comment]
Figure 12. MCMC 应该改为 HMC

**Comment by littlewu2508** [comment]
> Figure 12. MCMC 应该改为 HMC

包括 Caption

**Comment by littlewu2508** [comment]
sec 4.3 paragraph 4: In contrast to time 对比的是哪里？如果是相似的话，考虑用 “Similar to”？

**Comment by Berrysoft** [comment]
Page 19, line 3: an z^i -> a z^i

之前这里是 s 所以用了 an

**Comment by heroxbd** [comment]
> Page 9, Line 3: MLE like -> MLE-like

这个不改了，是 MLE, like eq. xxxx

**Comment by heroxbd** [comment]
> Page 11, Line 5: extracts -> extracted

这里麻烦了，前面的都用了现在时，为了保持一致，都应该改成过去时。

**Comment by heroxbd** [comment]
> Page 11, sixth-to-last line: but found -> but is found

不改了，前面有了 is.

**Comment by heroxbd** [comment]
> one-channelled

两种都可以，不改了。

**Comment by heroxbd** [comment]
> Page 14, line 8: fixed sample size Ns 后面加逗号

把 and associating 的 and 删了。

**Comment by Berrysoft** [comment]
sec 4.1, line 1: We constrain -> We constrained

**Comment by heroxbd** [comment]
> section 3.5.3, marginalizing out q 0 and z gives a flattened model -> marginalizing out q 0 and z, we arrives at a flattened model,

语法还行，不改了。

**Comment by Berrysoft** [comment]
sec 4.1, para 2:

> Like CNN, they are the fastest...

改为

> CNN is the fastest...

**Comment by Berrysoft** [comment]
sec 4.1, para 2:

> Fitting has ∼100 iterations, while LucyDDM and FSMP have ∼1000 iterations,

改为

> There are ~100 iterations in fitting, while ~1000 ones in LucyDDM and FSMP,

**Comment by littlewu2508** [comment]
On Wed, Jun 22, 2022 at 01:48:14AM -0700, Benda Xu wrote:
> > section 3.5.3, marginalizing out q 0 and z gives a flattened model -> marginalizing out q 0 and z, we arrives at a flattened model,
> 
> 语法还行，不改了。
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/heroxbd/waveform-analysis/issues/162#issuecomment-1162827020
> You are receiving this because you modified the open/close state.
> 
> Message ID: ***@***.***>

哦哦可以把前后两个分句看做两个单独的句子。最后的逗号需要改吗？

**Comment by heroxbd** [comment]
> sec 4.1, para 2:
> 
> > Fitting has ∼100 iterations, while LucyDDM and FSMP have ∼1000 iterations,
> 
> 改为
> 
> > There are ~100 iterations in fitting, while ~1000 ones in LucyDDM and FSMP,

不改了，虽然不是很规范，但是含义清楚，语法可以。

**Comment by Berrysoft** [comment]
> 意思是 waveform shifting, peaking finding, fourier deconvolution 与 CNN 一样快。

suboptimal: 次优的，指并不是最理想的或最令人满意的

**Comment by heroxbd** [comment]
> suboptimal

没问题，就是这个意思。

**Comment by heroxbd** [comment]
Dear Editor,

> 1. Please check that the names of all authors on the first page are
> spelt correctly.

Yes.

> 2. In JINST affiliations are written in the form:
> Department, University,
> Street, City, Country
> Please check each affiliation and provide the missing information if
> needed.

We have not specified street information because they are not commonly
used in postal addresses here.  We shall add them if you insist.

> 3. If an explicit acknowledgment of funding is required, please ensure
> that it is indicated in your article. If an Acknowledgments section is
> already present, please check that the information there is complete
> and correct.

We would like to update funding information on page 25, section
Acknowledgments, last sentence,

please change "This work is supported in part by the National Natural
Science Foundation of China (11620101004), ..." to "This work is
supported by the undergraduate innovative entrepreneurship training
programme of Tsinghua University, in part by the National Natural
Science Foundation of China (12127808, 11620101004), ..."


We find the following spelling or grammer updates.  It is a bit long, we
attach a annotated PDF file to help you locate the changes.  Thank you
so much for your time!

- Page 1 (contents), 4 (Table 1, line 10 definition of z), 16 (section
  title), "Hamilton Monte Carlo" to "Hamiltonian Monte Carlo".

  They are all cross-references, updating only the section title will
  update all the 3 places.

- Page 2, section 1, paragraph 2, line 1, "undergoes to development
  stages" to "undergoes two development stages".

- Page 2, section 2, paragraph 3, line 5, "the proximity of them" to
  "their proximity".

- Page 3, paragraph 1, line 1, "intercorelated" to "intercorrelated".

- Page 4, table 1, section 2, line 8, delete the entire line of "Δt0
  bias of a t 0 estimator 2.3.1 Time t0", this symbol is not used any
  more.

- Page 4, line 4, "for extra variance" to "for the extra variance".

- Page 5, paragraph 3, line 3-4, "To better model the rising edge
  curvature than Hamilton ..." to "To model the rising edge curvature
  better than Hamilton ...".

- Page 5, paragraph 3, line 9, "found reasonable match" to "found a
  reasonable match".

  "embracing underlying physics mechanism" to "embracing the underlying
  physics mechanism".

- Page 6, caption of figure 2, "Output charge $\hat{\bm{t}},
  \hat{\bm{q}}$ also in \subref{fig:pile}, which we will discuss in
  section~\ref{sec:algorithm}." to "We shall discuss the output charges
  $\hat{\bm{t}}, \hat{\bm{q}}$ of \subref{fig:pile} in
  section~\ref{sec:algorithm}".

- Page 6, section 2.3, line 4, "directly translate into" to "directly
  translates into".

- Page 6, section 2.3.1, paragraph 2, line 3, "substantial difference"
  to "a substantial difference".

- Page 6, section 2.3.1, paragraph 3, line 1, "Nevertheless, in general"
  to "In general".
  
- Page 7, eq. (2.7), formula after the second "=", the summation should
  be inside the "[ ]", "\frac{1}{Q_0}\sum_{i=1}^{N_\mathrm{PE}} \int
  \left[ q_i V_\mathrm{PE}(t-t_i) + \epsilon(t) \right] \mathrm{d} t" to
  "\frac{1}{Q_0} \int \left[\sum_{i=1}^{N_\mathrm{PE}} q_i
  V_\mathrm{PE}(t-t_i) + \epsilon(t) \right] \mathrm{d} t"

- Page 7, section 2.3.2, line 1 after eq. (2.8), "... distribution with
  a Gaussian jump" to "... distribution with a gamma jump".

- Page 8, line 1, "Resolution of" to "The resolution of".

- Page 8, section 3, line 2, "$\hat{N}_\mathrm{PE}$ and
  $\hat{N}_\mathrm{PE}$ is an estimator..." to "$\hat{N}_\mathrm{PE}$,
  an estimator...".

- Page 9, section 3.1.2, line after eq (3.6), "RSS will" to "RSS would".

- Page 11, section 3.2.1, paragraph 1, line 2, "sums up" to "summed up";

  line 3, "is used" to "was used";

  line 4, "superposes" to "superposed";

  line 5, "extracts pulse" to "extracted pulse".

- Page 11, section 3.2.1, paragraph 2, "shift them" to "and shift them";
  "a SER pulse" to "an SER pulse".

- Page 11, section 3.2.1, paragraph 3, line 2, "smaller than truth PE
  charges" to "smaller than true PE charges".

- Page 11, section 3.2.2, line 1, "Peak finding" to "peak finding".

- Page 12, figure 5 caption, delete the last sentence "Δt 0 is the bias
  of the t_KL estimator."

- Page 13, section 3.2.2, line before eq. (3.15), "a recurrence relation
  $\phi_*$ is" to "a recurrence relation for $\phi_*$ is".

- Page 14, section 3.4, paragraph 2, line 1, "an 1 dimensional vector"
  to "a 1-dimensional vector".

  line 2, "1 dimensional CNN" to "1-dimensional CNN".

  line 4, "and associating" to "associating".

- Page 14, section 3.4, paragraph 3, line 3, "is convoluted by" to "is
  convolved by".

- Page 14, section 3.4, paragraph 4-5, "$M$-channelled" to
  "$M$-channeled"; "$N$-channelled" to "$N$-channeled"; "one-channelled"
  to "one-channeled".

- Page 15, section 3.5, paragraph 2, line 3, "cross-dimensional issue"
  to "cross-dimensional issues".

- Page 16, section 3.5.1, line after eq. (3.22), "does not suffer at" to
  "does not suffer from".

- Page 17, section 3.5.2, line 2 after eq. (3.23), "normally distributed
  $q'_{j,1}$" to "gamma-distributed $q'_{j,1}$".

- Page 18, line after figure 10, "The charges" to "the charges".

- Page 19, paragraph 1, line 2, "by Metropolis-Hasings" to "by
  Metropolis-Hastings".

  line 3, "an $\bm{z}^i$ to "a $\bm{z}^i".

- Page 20, section 4.1, paragraph 2, line 4, "MCMC is too expansive" to
  "HMC is too expensive".

- Page 21, figure 12 and caption, "MCMC" to "HMC".  The figure is in
  .pgf format and can be updated inline.  I attach an updated figure
  just in case.

- Page 23, section 4.3, paragraph 1, line 1, "As
  figure~\ref{fig:summary}" to "In figure~\ref{fig:summary}".

Yours,
Benda

**Comment by heroxbd** [comment]
已经把 proof 反馈给编辑。
[proof-JINST_063P_1221.zip](https://github.com/heroxbd/waveform-analysis/files/8956308/proof-JINST_063P_1221.zip)
