### ISSUE TITLE
Proof of publication round 2

### ISSUE THREAD

**Issue by heroxbd** [heroxbd/waveform-analysis#163]
[JINST_063P_1221-r1.pdf](https://github.com/heroxbd/waveform-analysis/files/8965653/JINST_063P_1221-r1.pdf)

The final version of your paper is now ready for you to download from the Journal website.

Please check this final version and act, either to publish your paper (clicking on "ready for publication") or to request any further adjustments. In the latter case please use the button "send proofs" on your preprint page, listing your corrections.

**Comment by TakaraJikin** [comment]
看来基本上是最终稿了？

**Comment by heroxbd** [comment]
Takara Jikin ***@***.***> writes:

> 看来基本上是最终稿了？

嗯，只接受小修了。

**Comment by TakaraJikin** [comment]
1. 
3.1.3（小修改，也许也可以不修改）
虽然应用情形自动是两个1D的分布。 在 we can calculate 𝐷w from cumulative distribution functions (CDF)， 是否有必要说这是 for 1-dimensional distributions 
CDF的代用关系来自于scipy
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.wasserstein_distance.html
上面提出Compute the first Wasserstein distance between two 1D distributions.
我对于该方法是否能应用于二维分布最优输运不持有乐观态度

2.
虽然看上去非常独创，是否有必要进行重复检查？

**Comment by heroxbd** [comment]
最终我们没有修改，论文进入了发表流程。

**Comment by TakaraJikin** [comment]
赞， 什么时候能ORCID查到，需要手动加吗？还有在刊物发表以后，arxiv上是否有发表地址和版本的更新？目前google scholar能看到的只是两个之前的arxiv版本
