### ISSUE TITLE
重画 Figure 1

### ISSUE THREAD

**Issue by heroxbd** [heroxbd/waveform-analysis#17]
给出
tau=20, sigma=0
tau=0, sigma=5
tau=20, sigma=5
三种 light curve，用不出颜色着色

**Comment by heroxbd** [comment]
关错了，这个 commit 关联的是 https://github.com/heroxbd/waveform-analysis/issues/18

**Comment by thexdc** [comment]
确实是 https://github.com/heroxbd/waveform-analysis/issues/17，https://github.com/heroxbd/waveform-analysis/commit/4a83282e0a1b0052f7b285fe697ee23e5eeafd11 中 https://github.com/heroxbd/waveform-analysis/issues/18 没改完

**Comment by heroxbd** [comment]
这个 issue 是针对 Figure 1 的，是画与 Figure 3 对应的 绿、红、蓝三根线。

**Comment by thexdc** [comment]
我知道咋回事儿了，profile.pgf 在 commit 之前被我 checkout 没了

**Comment by heroxbd** [comment]
そうか
