### ISSUE TITLE
论文写作

### ISSUE THREAD

**Issue by littlewu2508** [heroxbd/waveform-analysis#2]
1. 按目录进行写作，大家先随便写，都是英文
2. 算法加benchmark（卷SPE-L2-Norm、可以尝试CNN拿它训练），CNN测试CPU，尝试给出flop计算量
3. 锦屏实际数据，实际数据的SPE
4. 有扰动的SPE模拟数据
5. *JUNO实际数据

**Comment by heroxbd** [comment]
改变了策略，全部采用 toyMC。

MISSION ACCOMPLISHED!
