### ISSUE TITLE
要不要画一个 LucyDDM 迭代步骤图？

### ISSUE THREAD

**Issue by heroxbd** [heroxbd/waveform-analysis#22]
因为 LucyDDM 被我们选为了核心的算法，而且是 FBMP 的第一步，要不要把它理解得更深刻一些，展示其迭代过程中，\hat{\phi}^n(t') 随 n 的变化？ @greatofdream @thexdc

**Comment by thexdc** [comment]
我觉得我们可以先看看结果，有必要的话在文章中放图

**Comment by thexdc** [comment]
[样例图片](https://cloud.tsinghua.edu.cn/f/9f1247dc56ac4eb08ae6/)

**Comment by thexdc** [comment]
经过讨论，Gradient Descent 等方法也是迭代方法，且在迭代步骤图中看不到新内容，于是决定不画。

MISSION ACCOMPLISHED!
