### ISSUE TITLE
加入 mu 估计

### ISSUE THREAD

**Issue by heroxbd** [heroxbd/waveform-analysis#27]
加入 mu 估计以体现我们的方法的能量重建优越性。

**Comment by thexdc** [comment]
FBMP 的 mu 估计，是采样得到的各个模型中的非 0 电荷的个数，被模型的各个后验概率加权的结果

**Comment by thexdc** [comment]
使用一次充分 FBMP 的采样结果，对 mu 和 t0 同时做拟合

**Comment by heroxbd** [comment]
> 使用一次充分 FBMP 的采样结果，对 mu 和 t0 同时做拟合

thumb-up 胜利在望

**Comment by heroxbd** [comment]
把准备用的图放到 overleaf 中吧
