### ISSUE TITLE
Figure 15 和 16 重叠太多

### ISSUE THREAD

**Issue by heroxbd** [heroxbd/waveform-analysis#28]
一个想法是把图放大成全宽，把 Figure 15 和 16 画在一起。只给一组 legend。

另一个想法是把最坏的波形分析方法去掉，让图更多专注于细节。

**Comment by thexdc** [comment]
把 Figure 15 和 16 画在一起的话，还是会叠在一起不易辨认。

这是一个 5 维图，(tau, sigma) - methods - mu - RSS - W-dist，很难画在一起。

这些方法中，Fitting 不能去掉，FBMP 和 CNN 不能去掉，LucyDDM 不建议去掉，那可能就得去掉 MCMC 了。后续对 MCMC 的论述比较少（主要会集中在如何引入混合模型上），不知道在这儿去掉 MCMC 会不会导致对其论述不充分。

**Comment by heroxbd** [comment]
MCMC 可以在详细性能评价中去掉，它在逻辑上是通向 FBMP 的一步。

**Comment by thexdc** [comment]
现在的版本中缩小了图片大小，感觉还行，是不是不用将 Fig 15 & 16 组合了？
