### ISSUE TITLE
Figure 17 优化

### ISSUE THREAD

**Issue by heroxbd** [heroxbd/waveform-analysis#29]
试一下把分母从 sigma_{1st} 换成 sigma_{ALL} 怎么样？这样纵轴的范围可以更小，现在 Figure 17 只能看到一个总体的趋势，这个趋势早在 Figure 3 就已经画清楚了。

另外，Figure 3 右图的红色为什么比 Figure 17 右图的黑色光滑呢？

**Comment by thexdc** [comment]
使用 sigma_{1st} 是为了和前面的图保持一致并给出各种方法相比于 (T_1,Q) 的提升程度；Figure 17 是老图，需要新画

**Comment by heroxbd** [comment]
> 使用 sigma_{1st} 是为了和前面的图保持一致并给出各种方法相比于 (T_1,Q) 的提升程度；

确实有这个优势，我也想试试相对于 sigma_{ALL} 的。sigma_xxx/sigma_{ALL} 可以给出好方法对 sigma_{ALL} 的逼近程度，并且 能避免各方法的线都叠在一起。如果想保持一致，可以把 Figure 3 的 sigma_{ALL}/sigma_{1st} 改成 sigma_{1st}/sigma_{ALL}。

> Figure 17 是老图，需要新画

**Comment by heroxbd** [comment]
改成 /sigma_{ALL} 试试？
