### ISSUE TITLE
完善论文论述

### ISSUE THREAD

**Issue by dachengx** [heroxbd/waveform-analysis#33]
- [x] #34
- [x] #35
- [x] #36
- [x] #37
- [x] #38
- [x] #39
- [x] #40 
- [x] #41 
- [x] #42 
- [x] #43

**Comment by heroxbd** [comment]
分成6个 issue

相应的 commit 加上
```
Closes: https://github.com/heroxbd/waveform-analysis/issues/NNN
```
自动关闭 issue

**Comment by heroxbd** [comment]
Done
