### ISSUE TITLE
确定图片中是否包括 FBMP_max

### ISSUE THREAD

**Issue by heroxbd** [heroxbd/waveform-analysis#35]

**Comment by thexdc** [comment]
我认为 FBMP 的使用场景中很少对 FBMP_max 有要求，而且引入 FBMP_max 会导致论述过程变得更加复杂，所以我认为不应该包括 FBMP_max。

**Comment by heroxbd** [comment]
> 我认为 FBMP 的使用场景中很少对 FBMP_max 有要求，而且引入 FBMP_max 会导致论述过程变得更加复杂，所以我认为不应该包括 FBMP_max。

赞同，如果 FBMP 可以全面超越 FBMP_max，那么应将 FBMP_max 去掉。为了论述的完整性，可以在正文中写"instead of full uncertainty propagation, the maximum posterior PE model could be used, but with less accuracy."
