### ISSUE TITLE
已经提交神经网络算法文本部分的写作

### ISSUE THREAD

**Issue by TakaraResearch** [heroxbd/waveform-analysis#4]
Latex Neural Network Writing finished.
Algorithm Mathematics Description should be added later.
Attention: All math parts should use the same set of descriptions, and should agree to the usage in other academics papers.

神经网络方法 文本描述已经添加到branch  后文应该添加实验细节和算法细节。
描述了两类算法 reconstruction， cdf-wasserstein， 我们的算法是他们的特例 matrix reconstruction l2; cdf-1-wasserstein。
考虑到论文的统一性，算法描述请后期添加（文中已经标出添加位置和添加方法）
推荐使用通用字符表例如：
e.g. data training X->Y   data prediction X'-->Y'  Training Function F...  Loss L ...

具体文章结构支持文本再组织

**Comment by heroxbd** [comment]
好的！

MISSION ACCOMPLISHED!
