### ISSUE TITLE
确定作者与致谢

### ISSUE THREAD

**Issue by dachengx** [heroxbd/waveform-analysis#40]

**Comment by heroxbd** [comment]
1.  @thexdc   问 Ghost-Hunter 决赛群，特别是当时的第二名，计算机系那位首位完成 CNN 的同学。
2.  @thexdc  整理好论文星期三发给陈老师。星期四在锦屏组会中作全面汇报，讨论作者列表。魏昌旭做了 fitting 工作，组会上讨论是否列为作者。
3.  @heroxbd 联系郭子溢，是否愿意成为作者，若不愿意，放在致谢中。
3. 大创的同学们都没有回复，放到致谢中。
4.  @heroxbd 问 xiaopeip 之外的 2019 年的小学期做过 waveform-analysis 大作业的同学想成为作者。若无人回应，不必放在致谢中。
5.  @heroxbd 问 Ghost Hunter 2019 组委会，是否愿意列为作者或名字出现在致谢中。默认只笼统致谢组委会。

新成为作者的同学需要把当前草稿精读一遍，提出修改意见。

**Comment by dachengx** [comment]
正文中添加 GitHub repo 链接？

**Comment by heroxbd** [comment]
Dacheng Xu ***@***.***> writes:

> 正文中添加 GitHub repo 链接？

不太方便写，可以在有了 arxiv 号之后，在 github repo 里的 README.md 上写
明它对应的论文。

**Comment by dachengx** [comment]
那看论文的人们怎么知道代码在哪儿呢？

**Comment by heroxbd** [comment]
Done

> 那看论文的人们怎么知道代码在哪儿呢？

把句子移动了一下位置。
