### ISSUE TITLE
对论文语言进行修饰

### ISSUE THREAD

**Issue by dachengx** [heroxbd/waveform-analysis#42]

**Comment by thexdc** [comment]
Comments by Prof. Chen: 

- [ ] 摘要最后一句来得突然，跟上一句逻辑上不能衔接
- [ ] 区分 timing measurement 和 time measurement
- [ ] "We can see that as method CNN uses Wasserstein distance as loss directly during training, its Wasserstein distance is the smallest. " 难以理解

Comments by Prof. Xu: 

- [ ] 以 RSS 为目标优化的 Fitting 是否做 alpha scaling 
- [ ] “sum(p_i) = mu by the normalization condition.” 应换为公式

Comments by Dr. Guo: 

- [ ] T_1-Q reduction第一次出现，最好解释一下 T_1-Q reduction是什么意思，以及参数 mu 的直观含义
- [ ] 章节 Evaluation criteria 讨论三种 criteria 的最优适用场景
- [ ] CNN 网络结构可以画得更 fancy 一些，参考深度学习文章中常见的画法
- [ ] 章节 Program efficiency 可以提一下需要训练的算法的训练耗时
- [ ] 章节 Summary and discussion 是否讨论了应用在探测器上时造成的变化？之前的研究是基于 toy MC 的数据集的，如果用在实际探测器上，各种先验分布的变化是否会造成可观的uncertainty？
