### ISSUE TITLE
Daya Bay 没有 FADC

### ISSUE THREAD

**Issue by heroxbd** [heroxbd/waveform-analysis#46]
都是 TDC/QDC ，需要修改 Reference。

**Comment by thexdc** [comment]
具体指的是哪部分文字？

**Comment by heroxbd** [comment]
Dacheng Xu ***@***.***> writes:

> 具体指的是哪部分文字？

Introduction 里 Daya Bay~\cite{huang_flash_2018}。这个研究不是大亚湾的主
体，它是为了 JUNO 准备，所以在大亚湾上测试的 FADC。

**Comment by heroxbd** [comment]
需要把 Daya Bay 归入 TDC/QDC 的几个实验中。

我没看出来 Daya Bay 在主体实验之后引入了 FADC 和我们的文章引用有什么冲突
毕竟这篇文章很强调波形分析，我看到其他文章中很少关注这一点

这篇文章的逻辑是，Daya Bay 只有 TDC 和 QDC ，需要建立一个完整的波形模型来预测 TDC 和 QDC 的行为

大亚湾实验组测量了 PMT 波形的性质，与大亚湾实验读取波形在其物理结果中应用波形分析，是两件事。我们在 review 中关注后者。

使用 TDC 和 QDC 就能得到每个 PE 的时间和电荷？

可以得到 threshold crossing time 和波形的积分

每个波形输出两个数

使用软件波形分析一定不会每个波形输出两个数吗

这个意义上讲是重叠的

所以我们开篇可以说“一切用PMT的实验都必须考虑波形分析”

随后，根据 Figure 3， TDC/QDC 只有在 mu -> 0 和 tau_l >> sigma_l 时有效，其它情况必须考虑更好的波形分析方法，于是有了我们的研究。

这是通篇的逻辑

**Comment by heroxbd** [comment]
有期刊的，使用期刊引用，不要用 arxiv
