### ISSUE TITLE
Waveform shifting 比 1st PE 法还差吗？

### ISSUE THREAD

**Issue by heroxbd** [heroxbd/waveform-analysis#48]
Waveform shifting 取了波形后面的时间信息，为什么比只取 1st PE 的结果要差？

**Comment by heroxbd** [comment]
t_1st 取的是波形的过阈时间，还是第1个 PE 的真实时间？

**Comment by thexdc** [comment]
> 图3中的 t_1st 取的是波形的过阈时间，还是第1个 PE 的真实时间？

图 3 中的 t_1st 取的是第 1个 PE 的真实时间

**Comment by heroxbd** [comment]
Dacheng Xu ***@***.***> writes:

> 图 3 中的 t_1st 取的是第 1个 PE 的真实时间

这与我们在正文写的 waveform rising edge (修改前) 和 threshold crossing
time (修改后) 不符。需要改正文或改图。

**Comment by heroxbd** [comment]
思考了半小时，我觉得应画一个 threshold crossing time 的新图：

1. 论文开篇讲的是经典的测量方法是 TDC，TDC 的原理是 threshold crossing time。图的目标是指出 TDC 方法到 t_ALL 理想方法有多大差距，我们研究波形分析有多大的提升空间。
2. 波形分析最菜的 waveform shifting 可以看作是 threshold crossing time 的扩展，不只取第一个过阈时刻，而是取了所有过阈时刻。那么后文在 waveform shifting 中可以论述，虽然这个方法简陋，但是依旧相比 TDC 有了进步。
3. 有可能第一个 PE 的真实时间与 threshold crossing time 没什么区别，如果是这样更好，我们检查确认一下两者的等价性。

**Comment by thexdc** [comment]
> 这与我们在正文写的 waveform rising edge (修改前) 和 threshold crossing time (修改后) 不符。需要改正文或改图。

逻辑是我们要找到 t_1st，TDC 用了 threshold crossing time，我们要论述的是用 第一个 PE 的时间也不会比 用所有 PE 好，那么用 threshold crossing time 就会更不好

直接改论文就行了

**Comment by thexdc** [comment]
论文中的 $\hat{t}_\mathrm{1st}$ 和 $\hat{t}_\mathrm{ALL}$ 值得都是 t0 的 estimator，只不过前者用的是第一个 PE，后者用的是所有 PE

**Comment by thexdc** [comment]
[vs-deltadiv-thres.pdf](https://github.com/heroxbd/waveform-analysis/files/7072362/vs-deltadiv-thres.pdf) 是 threshold 得到的 first PE 的 time resolution

[vs-deltadiv.pdf](https://github.com/heroxbd/waveform-analysis/files/7072364/vs-deltadiv.pdf) 是 true first PE 得到的 time resolution

可以看到区别不大

**Comment by thexdc** [comment]
> 思考了半小时，我觉得应画一个 threshold crossing time 的新图：
> 
> 1. 论文开篇讲的是经典的测量方法是 TDC，TDC 的原理是 threshold crossing time。图的目标是指出 TDC 方法到 t_ALL 理想方法有多大差距，我们研究波形分析有多大的提升空间。
> 2. 波形分析最菜的 waveform shifting 可以看作是 threshold crossing time 的扩展，不只取第一个过阈时刻，而是取了所有过阈时刻。那么后文在 waveform shifting 中可以论述，虽然这个方法简陋，但是依旧相比 TDC 有了进步。
> 3. 有可能第一个 PE 的真实时间与 threshold crossing time 没什么区别，如果是这样更好，我们检查确认一下两者的等价性。

3. 确实没很大区别

**Comment by heroxbd** [comment]
> [vs-deltadiv-thres.pdf](https://github.com/heroxbd/waveform-analysis/files/7072362/vs-deltadiv-thres.pdf) 是 threshold 得到的 first PE 的 time resolution
> 
> [vs-deltadiv.pdf](https://github.com/heroxbd/waveform-analysis/files/7072364/vs-deltadiv.pdf) 是 true first PE 得到的 time resolution
> 
> 可以看到区别不大

好的。可以在正文提一句两者的等价性。
