### ISSUE TITLE
Overleaf协同编辑机制

### ISSUE THREAD

**Issue by thexdc** [heroxbd/waveform-analysis#5]
现在Note已经上传到gravity网络的overleaf上了，可以进行在线协同编辑。

但接入gravity需要配置一下网络，且overleaf和github上的Note编辑是竞争关系需要清除其中一个（清除github上的Note）。

**Comment by heroxbd** [comment]
MISSION ACCOMPLISHED!

计划是这样：当前我们使用 github 协同。五人和更多人编辑时使用 overleaf 协同。最后在 TJJK/publication 存档。
