### ISSUE TITLE
xiaopeip LASSO 复现

### ISSUE THREAD

**Issue by heroxbd** [heroxbd/waveform-analysis#50]
如何复现“xiaopeip + LASSO 对结果无影响"的论断？

加了 LASSO，参数 1000，不加 threshold，与参数为 0 不加 threshold 的 结果相比 W-dist 变大了，RSS 变大了，mu resolution 变坏了14:53

但是 参数为 0 不加 threshold 的结果 mu 有 大于 0 的 bias，加了 LASSO，参数 1000 mu 没有 bias14:54

详见 result/xiaopeip/ 和 result/xiaopeip-100014:54

LBFGSB 的收敛性检查过了14:56

全都是收敛的14:57

加了 LASSO，参数 1000，不加 threshold，与参数为 0 不加 threshold 的 结果相比 W-dist 变大了，RSS 变大了，mu r
Dacheng Xu

除了 1000 取其它值呢？15:06

在画图15:16

好15:18

参数为 10 与 参数为 1000 结果类似

**Comment by heroxbd** [comment]
@thexdc 关于“限制了 q 为正的 RSS 拟合对一个额外的 LASSO 正则项不敏感”的试验观察和猜想已经有严格的证明。该论文是在 NIPS 2011 会议上发表的同作者的严谨版。我已经加倒 zotero 里。

这样我们已经对 direct charge fitting 的行为彻底理解了，它为 MCMC 和 FBMP 提供了坚实的理论基础。

Slawski, Martin, and Matthias Hein. “Non-Negative Least Squares for High-Dimensional Linear Models: Consistency and Sparse Recovery without Regularization.” Electronic Journal of Statistics 7, no. none (January 2013): 3004–56. https://doi.org/10.1214/13-EJS868.

**Comment by thexdc** [comment]
需要在论文中加几句话强调一下并引用文献吗？

**Comment by heroxbd** [comment]
在 e0df35e63c76be23dcdac60f4622ddaae35e8692 加入了此说明。
