### ISSUE TITLE
指出式 (2.3) 与地震学中 sparse spike train 的联系

### ISSUE THREAD

**Issue by heroxbd** [heroxbd/waveform-analysis#51]
完善论文的引用 。

**Comment by thexdc** [comment]
添加这个引用的目的是什么？

**Comment by heroxbd** [comment]
> 添加这个引用的目的是什么？

点明我们的 formulation 不是凭空冒出来的，而是有历史渊源。事实上确实如此，先有了 spike-train model，后有了 direct charge fitting

**Comment by thexdc** [comment]
引用率较高的参考文献：https://library.seg.org/doi/10.1190/1.1441261
