### ISSUE TITLE
Figure 10 的 threshold

### ISSUE THREAD

**Issue by heroxbd** [heroxbd/waveform-analysis#52]
最终 charge fitting 是否需要 threshold? 如果不需要，应当把 Figure 10 中的绿线去掉。

**Comment by heroxbd** [comment]
如果需要，我们可能需要迭代。

**Comment by thexdc** [comment]
在 Direct charge fitting 中，需要在初始化参数的时候做 threshold；在 Waveform shift 中需要做 threshold；在 Peak finding 和 Fast deconvolution 中需要做 threshold，避免噪声的存在影响 peak 的判断；在 Fast Bayesian matching pursuit 和 Markov Chain Monte Carlo 中需要做 threshold；在 Richardson-Lucy direct deconvolution 中需要去掉结果中的 fragments

实际上完全不需要做 threshold 的只有 CNN，它在学习过程中学到了 threshold 有多大

**Comment by heroxbd** [comment]
Dacheng Xu ***@***.***> writes:

> 在 Direct charge fitting 中，需要在初始化参数的时候做 threshold；

初始化参数指什么？

> 在 Waveform shift 中需要做 threshold；在 Peak finding 和 Fast
> deconvolution 中需要做 threshold，避免噪声的存在影响 peak 的判断；在
> Fast Bayesian matching pursuit 

FBMP 的 threshold 是对 MMSE 之后的 q 进行 threshold 吗？

> 和 Markov Chain Monte Carlo 中需要做 threshold；在 Richardson-Lucy
> direct deconvolution 中需要去掉结果中的 fragments
>
> 实际上完全不需要做 threshold 的只有 CNN，它在学习过程中学到了
> threshold 有多大

哦，但是它需要 alpha scaling.

**Comment by thexdc** [comment]
Direct charge fitting 中的初始化参数指的是找到那些 time bin 可能有 PE；FBMP 中 threshold 的用途也只是与 Direct charge fitting 相同地初始化参数

**Comment by heroxbd** [comment]
Dacheng Xu ***@***.***> writes:

> Direct charge fitting 中的初始化参数指的是找到那些 time bin 可能有 PE；
> FBMP 中 threshold 的用途也只是与 Direct charge fitting 相同地初始化参数

这一部分叫做 sparse initialization。

我的问题是另一个：DCF 输出的 \hat{q} 还经过 threshold 吗？如果不经过，
Figure 10b 里的绿线代表什么？

**Comment by thexdc** [comment]
> 这一部分叫做 sparse initialization。 我的问题是另一个：DCF 输出的 \hat{q} 还经过 threshold 吗？如果不经过， Figure 10b 里的绿线代表什么？

DCF 输出的 \hat{q} 不经过 threshold；代表初始化，看看什么位置是“需要拟合的波形”

**Comment by heroxbd** [comment]
Dacheng Xu ***@***.***> writes:

> DCF 输出的 \hat{q} 不经过 threshold；代表初始化，看看什么位置是“需要拟合的波形”

是不是 Figure 10b 里的图就不需要标 threshold 线了？

**Comment by thexdc** [comment]
> 是不是 Figure 10b 里的图就不需要标 threshold 线了？

threshold 在算法中起作用了，也许留着比较好

**Comment by heroxbd** [comment]
Dacheng Xu ***@***.***> writes:

> threshold 在算法中起作用了，也许留着比较好

他起的作用是在 LucyDDM 中，这一点已经在 Figure 7 中展示了。 DCF 没有引入
额外的 threshold 就不应该画

**Comment by thexdc** [comment]
> DCF 输出的 \hat{q} 不经过 threshold；代表初始化，看看什么位置是“需要拟合的波形”

这里面没有用 LucyDDM 做初始化，而是首先寻找超过 threshold 的波形，然后向两边延拓。即 DCF 与 FBMP 使用的是不是同一种初始化。有两点原因：当时测试 DCF 的时候 LucyDDM 不成熟，不能将 LucyDDM 的影响引入；FBMP 有时候可能需要先验，而“过阈-延拓”作为一个极其简单的波形分析方法，不能给出先验，且提供的 time bin 自由度太多，不利于 MCMC 和 FBMP。

**Comment by heroxbd** [comment]
Dacheng Xu ***@***.***> writes:

> 这里面没有用 LucyDDM 做初始化，而是首先寻找超过 threshold 的波形，然后
> 向两边延拓。

使用这样的方法，应当在正文中论述。

> 即 DCF 与 FBMP 使用的是不是同一种初始化。有两点原因：当时测试 DCF 的时
> 候 LucyDDM 不成熟，不能将LucyDDM 的影响引入；

现在 LucyDDM 成熟了，是否可以统一使用 LucyDDM 初始化？

> FBMP 有时候可能需要先验，而“过阈-延拓”作为一个极其简单的波形分析方法，
> 不能给出先验，且提供的 time bin 自由度太多，不利于 MCMC 和 FBMP。

ELBO 比较给出了 FBMP 不需要 LucyDDM 先验，这个考虑还必要吗？

**Comment by thexdc** [comment]
我试试 DCF 的 LucyDDM 初始化吧，合适的话就给换上去

**Comment by heroxbd** [comment]
Dacheng Xu ***@***.***> writes:

> 我试试 DCF 的 LucyDDM 初始化吧，合适的话就给换上去

好的，感谢！

**Comment by heroxbd** [comment]
使用 LucyDDM 初始化结果变差了，怎么理解？

**Comment by thexdc** [comment]
主要是 low NPE 的时候变差了，现在看起来，在低 PE 的时候，“过阈-延拓” 给出了比 LucyDDM 初始化更少的参数。

LucyDDM 初始化也是有超参的，现在使用的超参与 FBMP 中的 LucyDDM 超参相同

**Comment by thexdc** [comment]
我稍微改了参数，没什么太多变化。在 time resolution 那张图中 DCF 有点坏主要是因为 离群值，time resolution 作为一个 标准差，离群值对其影响很大

![photo1630311873](https://user-images.githubusercontent.com/40532474/131309652-695422d0-961d-49dd-a022-9e55ebbd9c6c.jpeg)

**Comment by heroxbd** [comment]
> 主要是 low NPE 的时候变差了，现在看起来，在低 PE 的时候，“过阈-延拓” 给出了比 LucyDDM 初始化更少的参数。
> 
> LucyDDM 初始化也是有超参的，现在使用的超参与 FBMP 中的 LucyDDM 超参相同

“过阈-延拓” 初始化更少的参数，是因为 LucyDDM 反卷积容易给出来一些假信号吗？

**Comment by thexdc** [comment]
> 主要是 low NPE 的时候变差了，现在看起来，在低 PE 的时候，“过阈-延拓” 给出了比 LucyDDM 初始化更少的参数。
> 
> LucyDDM 初始化也是有超参的，现在使用的超参与 FBMP 中的 LucyDDM 超参相同

这个论断有误，我错了。

事实上是在 LucyDDM 初始化的过程中使用了一个 charge threshold，来判断是否某一个 time bin 真的有 PE 而不是噪声的影响。在 FBMP 中使用的这个 charge threshold 比较低，这是为了避免初始化的因素使得 mu bias 小于 0.

目前看到的 “过阈-延拓” 给出了比 LucyDDM 初始化**更多**的参数。而前面提到的“离群值”，来自 LucyDDM 初始化的过程中使用的一个 charge threshold 过低，而 DCF 没有模型选择，所以得到了一些 fragments。FBMP 具有模型选择功能，所以即使这个 charge threshold 参数不对，也不太影响 FBMP。

我现在将这个 charge threshold 提高一些看看效果。目前初步试验（mu=0.5）表明提高 charge threshold 可以减少离群值。

**Comment by heroxbd** [comment]
> > 主要是 low NPE 的时候变差了，现在看起来，在低 PE 的时候，“过阈-延拓” 给出了比 LucyDDM 初始化更少的参数。
> > LucyDDM 初始化也是有超参的，现在使用的超参与 FBMP 中的 LucyDDM 超参相同
> 
> 这个论断有误，我错了。
> 
> 事实上是在 LucyDDM 初始化的过程中使用了一个 charge threshold，来判断是否某一个 time bin 真的有 PE 而不是噪声的影响。在 FBMP 中使用的这个 charge threshold 比较低，这是为了避免初始化的因素使得 mu bias 小于 0.
> 
> 目前看到的 “过阈-延拓” 给出了比 LucyDDM 初始化 _更多_ 的参数。而前面提到的“离群值”，来自 LucyDDM 初始化的过程中使用的一个 charge threshold 过低，而 DCF 没有模型选择，所以得到了一些 fragments。FBMP 具有模型选择功能，所以即使这个 charge threshold 参数不对，也不太影响 FBMP。
> 
> 我现在将这个 charge threshold 提高一些看看效果。目前初步试验（mu=0.5）表明提高 charge threshold 可以减少离群值。

明白，这个观察很合理。如果时间紧迫，必要的话我们可以在正文中说明剔除离散值，给出主体的趋势。

**Comment by thexdc** [comment]
> 明白，这个观察很合理。如果时间紧迫，必要的话我们可以在正文中说明剔除离散值，给出主体的趋势。

no prob 我相信新的合理的 configuration 将在今晚出现

**Comment by thexdc** [comment]
我们一定要求 FBMP 和 DCF 使用同样配置的初始化吗？

**Comment by thexdc** [comment]
已经为 DCF 和 FBMP 更新了相同的初始化过程，确实 FBMP 对 charge threshold 不敏感

**Comment by heroxbd** [comment]
Dacheng Xu ***@***.***> writes:

> 我们一定要求 FBMP 和 DCF 使用同样配置的初始化吗？

想设备成不同的 threshold 吗？

**Comment by thexdc** [comment]
> 想设备成不同的 threshold 吗？

不需要，对优化没有作用。目前已经是一样的了。
