### ISSUE TITLE
明确 boxplot 的定义

### ISSUE THREAD

**Issue by heroxbd** [heroxbd/waveform-analysis#53]
boxplot 的五个值是 中位数, 25%, 75％ 和 正负 3 sigma 吗？

**Comment by thexdc** [comment]
https://matplotlib.org/stable/_images/boxplot_explanation.png

两个 whisker 不是很容易定义，但是我们可以引用文献（http://theta.edu.pl/wp-content/uploads/2012/10/exploratorydataanalysis_tukey.pdf），也可以直接定义成任何 quantile

**Comment by heroxbd** [comment]
Dacheng Xu ***@***.***> writes:

> https://matplotlib.org/stable/_images/boxplot_explanation.png
>
> 两个 whisker 不是很容易定义，但是我们可以引用文献（http://theta.edu.pl/wp-content/uploads/2012/10/exploratorydataanalysis_tukey.pdf），也可以直接定义成任何 quantile

说明是 matplotlib 默认，并且给出默认的定义即可。

**Comment by thexdc** [comment]
> 说明是 matplotlib 默认，并且给出默认的定义即可。

如果我们仔细看那张图，会发现默认的定义不容易描述。

**Comment by heroxbd** [comment]
Dacheng Xu ***@***.***> writes:

> 如果我们仔细看那张图，会发现默认的定义不容易描述。

那就写一段话来描述。

**Comment by thexdc** [comment]
现在的版本里面只有 FBMP 提到了 box plot，是不是要在第一次出现 box plot 的时候提到 box plot，以及我记得之前第一次出现 box plot 的时候就文字中有提到 box plot

**Comment by thexdc** [comment]
https://matplotlib.org/stable/_images/boxplot_explanation.png 这个图的协议是 CC BY 4.0，我们在文章中应该可以直接给链接？

**Comment by heroxbd** [comment]
Dacheng Xu ***@***.***> writes:

> https://matplotlib.org/stable/_images/boxplot_explanation.png 这个图的协议是 CC BY 4.0，我们在文章中应该可以直接给链接？

这个链接过了一年换了 URL 怎么办？

**Comment by heroxbd** [comment]
Dacheng Xu ***@***.***> writes:

> 现在的版本里面只有 FBMP 提到了 box plot，是不是要在第一次出现 box plot
> 的时候提到 box plot，以及我记得之前第一次出现 box plot 的时候就文字中
> 有提到 box plot

从 CNN 就有了 boxplot。不是纠结字面上 boxplot 是啥，是画了一张图，就应当
把图里的每一处都讲清楚。

**Comment by thexdc** [comment]
> 从 CNN 就有了 boxplot。不是纠结字面上 boxplot 是啥，是画了一张图，就应当 把图里的每一处都讲清楚。

但是我现在找不到能在哪儿放介绍 box plot 的文字，因为 CNN 的 box plot 的字样改没啦

**Comment by heroxbd** [comment]
> > 从 CNN 就有了 boxplot。不是纠结字面上 boxplot 是啥，是画了一张图，就应当 把图里的每一处都讲清楚。
> 
> 但是我现在找不到能在哪儿放介绍 box plot 的文字，因为 CNN 的 box plot 的字样改没啦
> 
> 修改的过程中偶尔没注意 consistency，某些内容消失了
> 
> 之前出现过的大多数 box plot 都消失了，所以我也不知道在哪儿加才能避免它们再次被删掉

在第一次出现时，即 CNN 图上解释 boxplot 的五个点含义，其它图的说明引用此图。
