### ISSUE TITLE
Figure 12 算 z 和 q 时，用 p(z) 了吗？

### ISSUE THREAD

**Issue by heroxbd** [heroxbd/waveform-analysis#55]
我们已经在计算 model selection metric nu 中去掉了先验，Figure 12 中的 z 和 q 估计是不是带先验的？

**Comment by thexdc** [comment]
不带先验，这个图有什么不正常吗？

**Comment by heroxbd** [comment]
Dacheng Xu ***@***.***> writes:

> 不带先验，这个图有什么不正常吗？

正常，只是确认前后的条件是否一致。

**Comment by heroxbd** [comment]
\hat{\bm{z}} &= \arg \underset{\bm{z}}{\max} p(\bm{w}|\bm{z}) \\

**Comment by thexdc** [comment]
是 z = arg max p(w|z)，FBMP 不能精确计算 p(z|w)

**Comment by heroxbd** [comment]
Dacheng Xu ***@***.***> writes:

> 是 z = arg max p(w|z)，FBMP 不能精确计算 p(z|w)

好的！
