### ISSUE TITLE
Wasserstein distance 与 pile-up 的关系

### ISSUE THREAD

**Issue by thexdc** [heroxbd/waveform-analysis#56]
CNN section 出现了

> $D_w$ stops increasing with $N_\mathrm{PE}$ at about 6 PEs, showing CNN performs well in $D_w$ at large pile-ups. 

其实在高 PE 的部分 D_w 变化不大是 D_w 自身的特性

比如对相同数据集的 Waveform shifting 的结果：

[thresholdchargestats.pdf](https://github.com/heroxbd/waveform-analysis/files/7071858/thresholdchargestats.pdf)

**Comment by heroxbd** [comment]
好的，需要改一下这里的结论。
