### ISSUE TITLE
白噪声的 sigma 是多少？

### ISSUE THREAD

**Issue by heroxbd** [heroxbd/waveform-analysis#59]
1mV 吗？

**Comment by heroxbd** [comment]
如果是这样，总共 180 个采样点，RSS 应服从 df=180 的 chi2 分布，均值在 180。为什么 FBMP 可以给出 15.8mV^2， DCF 可以给出 7.63mV^2 的结果？

**Comment by thexdc** [comment]
所有计算的 RSS 中，原始波形都是不带噪声的。否则波形分析带来的影响将可能是小量。

Note 中的 RSS 定义和现在计算方法不一致

**Comment by heroxbd** [comment]
Dacheng Xu ***@***.***> writes:

> 所有计算的 RSS 中，原始波形都是不带噪声的。否则波形分析带来的影响将可能是小量。
>
> Note 中的 RSS 定义和现在计算方法不一致

正文中需要明确区分用于评估算法性能的 RSS[\tilde{w}, \hat{w}] 和 alpha
scaling 用的 RSS[\hat{w}, w]。
