### ISSUE TITLE
论文需要完善的部分

### ISSUE THREAD

**Issue by thexdc** [heroxbd/waveform-analysis#6]
- [x] Makefile：增加对mu、sigma、tau的遍历
- [x] vs.py：增加对mu、sigma、tau的各种组合的时间分辨率提升的描述图片
- [x] test_dist.py：对比使用RSS进行拟合的RSS残差与用W-dist神经网络的到的RSS残差的大小
- [x] Introduction.tex：详细介绍toyMC和时间分辨率提升的意义
- [x] fit.py：补充新的MCMC方法
- [x] Wdist.tex：详细论述wdist的优势以及对时间分辨率提升的优势
- [x] Algorithm.tex：详细论述时间分辨率提升的情况，形成环形论述，wdist加入箱线图
- [x] Conclusion.tex：加入展望和未来工作，分析方法的不足和可扩展空间
- [x] 检查所有语法、符号错误

**Comment by heroxbd** [comment]
好的，还有一点是我希望按照 smoke 的公式加上 MCMC 的方法对比。我猜测效果会比纯 fit 好。

**Comment by heroxbd** [comment]
MISSION ACCOMPLISHED!
