### ISSUE TITLE
demo 之间的比较问题

### ISSUE THREAD

**Issue by thexdc** [heroxbd/waveform-analysis#60]
我看到现在 Caption 中进行了对单个例子的 demo 的三个 criteria 的比较

是否这种比较能够反映算法的 performance，尤其是考虑到单一样本不能代表整体

**Comment by heroxbd** [comment]
> 我看到现在 Caption 中进行了对单个例子的 demo 的三个 criteria 的比较
> 
> 是否这种比较能够反映算法的 performance，尤其是考虑到单一样本不能代表整体

不能当作证据，只要做为描述算法的 demo
