### ISSUE TITLE
Figure 4 (a)(b)

### ISSUE THREAD

**Issue by heroxbd** [heroxbd/waveform-analysis#64]
(a) (b) 两图的纵轴 0 值能否对齐？

**Comment by thexdc** [comment]
[charge.pdf](https://github.com/heroxbd/waveform-analysis/files/7352776/charge.pdf)
[wave.pdf](https://github.com/heroxbd/waveform-analysis/files/7352777/wave.pdf)
这样？

**Comment by thexdc** [comment]
![charge](https://user-images.githubusercontent.com/40532474/137491049-08db17d7-0d78-4cd0-affa-a98af49e87d7.png)

我觉得这样看着还不错。

**Comment by heroxbd** [comment]
嗯，这个好！
