### ISSUE TITLE
ELBO 计算 bug

### ISSUE THREAD

**Issue by dachengx** [heroxbd/waveform-analysis#65]
因为此 [line](https://github.com/heroxbd/waveform-analysis/blob/master/bayesian.py#L254) 的存在，我们对 ELBO 的计算存在 bug。现在将重新计算各配置下的 ELBO，并修改文件：bat:/mnt/stage/xdc/result/prior.md。Thanks to: @greatofdream

**Comment by dachengx** [comment]
之前测试中 RGS 后选取解的个数是确定的（按概率排序 30 个），在将选取条件为修改为“选取的解的概率，不比最大概率的解之概率小100倍”之后的测试结果为：

# Test of configurations by ELBO

$\mu$=10

| $\tau$/ns | $\sigma$/ns | prior | space | ELBO |
| ----- | ----- | ----- | ----- | ----- |
| 0 | 5 | no | w/ | -199.88 |
| 0 | 5 | lucy | w/ | -200.12 |
| 0 | 5 | profile | w/ | -199.03 |
| 0 | 5 | no | w/o | -199.85 |
| 0 | 5 | lucy | w/o | -200.06 |
| 0 | 5 | profile | w/o | -199.28 |
| 20 | 5 | no | w/ | -275.73 |
| 20 | 5 | lucy | w/ | -276.15 |
| 20 | 5 | profile | w/ | -275.47 |
| 20 | 5 | no | w/o | -275.79 |
| 20 | 5 | lucy | w/o | -276.09 |
| 20 | 5 | profile | w/o | -275.45 |

**Comment by dachengx** [comment]
虽然 profile+w/space 的 ELBO 在 tau = 20 和 sigma = 5 的时候比 profile+w/ospace 稍差。但是其在  tau = 0 和 sigma = 5 时很强。最终选用 profile+w/space.

**Comment by heroxbd** [comment]
Dacheng Xu ***@***.***> writes:

> 虽然 profile+w/space 的 ELBO 在 tau = 20 和 sigma = 5 的时候比
> profile+w/ospace 稍差。但是其在 tau = 0 和 sigma = 5 时很强。最终选用
> profile+w/space.

好的！
