### ISSUE TITLE
把 Figure 13 与 Table 1 结合起来

### ISSUE THREAD

**Issue by heroxbd** [heroxbd/waveform-analysis#68]
Figure 13 的信息量太小，Table 1 的数字也太单薄。

画一个二维图怎么样？横轴是耗时，纵轴是 D_w 分布。

按照与宝尔金讨论，CNN 的耗时用 CPU 再计一次，便于跟其它方法比较。

**Comment by thexdc** [comment]
![summarycharge](https://user-images.githubusercontent.com/40532474/138385210-5626fe50-4ab8-4630-9c5f-724bb842782a.png)
这张如何？
