### ISSUE TITLE
Figure 14(b) 的 y 轴上限设为 0.5

### ISSUE THREAD

**Issue by heroxbd** [heroxbd/waveform-analysis#71]
突出 LucyDDM 之外3个方法的比较。

**Comment by thexdc** [comment]
> > > > Figure 14(a) 的 y 轴分别截断在 1.0 和 2.0 上
> > > 
> > > 
> > > “分别截断”是啥意思？
> > 
> > 
> > (a) 左在 1.0 截断，(a) 右在 2.0 截断
> 
> 使用双纵坐标轴吗？

nvm
