### ISSUE TITLE
delta_truth vs delta_1st 的比较

### ISSUE THREAD

**Issue by heroxbd** [heroxbd/waveform-analysis#8]
两者比较还是例举6种情况较好。因为可以通过 sigma = 0 的情况论述为什么过去人们认为只取 t_1 就够了。

**Comment by thexdc** [comment]
4 种就够了吧，之前说 6 种太多了

**Comment by heroxbd** [comment]
> 4 种就够了吧，之前说 6 种太多了

好，sigma=0 tau=20 一种，其它 sigma=10, 20 等再加三种

**Comment by thexdc** [comment]
The commit is [here.](https://github.com/heroxbd/waveform-analysis/commit/77957fd2302bee7f5c1b8b1fdac652aff2fa4dcb) 

MISSION ACCOMPLISHED!

**Comment by heroxbd** [comment]
Yaaaay!

可以在 commit message 里写：

```
Closes: https://github.com/heroxbd/waveform-analysis/issues/8
```
这样 Github 会自动关 issue。

**Comment by heroxbd** [comment]
还需要一个 sigma=0 的极端情况，用以说明为什么大家曾经认为只要第一个 PE 就够了。

**Comment by heroxbd** [comment]
如果加图例，就把两条线都画出来，不用 ratio。如果用 ratio 就不必画图例了。

我倾于前者

**Comment by heroxbd** [comment]
如果画 ratio，它们都可以用不同颜色放在一个图中。

**Comment by heroxbd** [comment]
MISSION ACCOMPLISHED!
