### ISSUE TITLE
当second=0的时候，first计算会被算到最后一个step

### ISSUE THREAD

**Issue by greatofdream** [heroxbd/waveform-analysis#87]
https://github.com/heroxbd/waveform-analysis/blob/64cf8ab5d982327b2d9c801f21bd39d0b6a18713/mu.py#L142

`steps[second - 1]` step[-1]是最后一个step，`es_history = es_history[first:]`只有最后一个值

**Comment by heroxbd** [comment]
是这样的，但为什么 second 会等于 0?

**Comment by heroxbd** [comment]
这说明你从起始到 burning 的步骤中，链的状态没有任何改变。

**Comment by greatofdream** [comment]
是的，我发现有些事例到burning对应的步数8000//5之后才开始变化

**Comment by greatofdream** [comment]
> 这说明你从起始到 burning 的步骤中，链的状态没有任何改变。

也就是说这些事例可能对应的迭代次数不够

**Comment by heroxbd** [comment]
嗯，`mu.py` 应该修改一下。

**Comment by heroxbd** [comment]
Done
