### ISSUE TITLE
确认 FSMP 的 \hat{z} 和 \hat{q} 是否是按照 (3.20) 给出的

### ISSUE THREAD

**Issue by heroxbd** [heroxbd/waveform-analysis#89]
更新 Figure 11 的例子。

**Comment by dachengx** [comment]
可以确认，在[文件](https://github.com/heroxbd/waveform-analysis/blob/620579c29f9e2133fd9a7498d42a1c226ed79c90/latexdemo.ipynb)中已经修改

**Comment by dachengx** [comment]
> 可以确认，在 [jupyter notebook](https://github.com/heroxbd/waveform-analysis/blob/620579c29f9e2133fd9a7498d42a1c226ed79c90/latexdemo.ipynb) 的 cell 10 中已经修改。

数值不是很对。我再查一下。

**Comment by dachengx** [comment]
数值变了是因为我忘设置随机数种子了。
