### ISSUE TITLE
结论中丢失了波形分析对时间 resolution 的重要性？

### ISSUE THREAD

**Issue by littlewu2508** [heroxbd/waveform-analysis#94]
在 summary 中提出，对于 mu 很大的情况下，任何波形分析都会比没有波形分析得到更好的 t0 估计，这是一个有价值的结论，应该在 Conclusion 中再提一次

**Comment by heroxbd** [comment]
littlewu2508 ***@***.***> writes:

> 在 summary 中提出，对于 mu 很大的情况下，任何波形分析都会比没有波形分
> 析得到更好的 t0 估计，这是一个有价值的结论，应该在 Conclusion 中再提一
> 次

有道理，你来起草一句话，放在 conclusion 和 abstract 里，我来整合。

**Comment by littlewu2508** [comment]
> littlewu2508 ***@***.***> writes:
> 在 summary 中提出，对于 mu 很大的情况下，任何波形分析都会比没有波形分 析得到更好的 t0 估计，这是一个有价值的结论，应该在 Conclusion 中再提一 次
> 有道理，你来起草一句话，放在 conclusion 和 abstract 里，我来整合。

写好了 : https://github.com/heroxbd/waveform-analysis/commit/e610fd4d9e2538249f2b8c6a5a0baf3ce997d043

**Comment by heroxbd** [comment]
Done
