### ISSUE TITLE
Line 95: This number 0.25 for the relative variance of the gain seems rather small. It would correspond to a first stage gain of 16. A much more reasonable gain variance is ∼ 0.4 which corresponds to first stage gain of∼ 6. However this creates a problem for the model if the gain is assumed to fluctuate as a Gaussian. A much more reasonable assumption is a gamma distribution as is well known in the literature.

### ISSUE THREAD

**Issue by heroxbd** [heroxbd/waveform-analysis#99]

**Comment by dachengx** [comment]
Addressed in e9383d5613168161f9746ac2dbdc1d76c12bbb3a

**Comment by heroxbd** [comment]
> A much more reasonable assumption is a gamma distribution as is well known in the literature.

@littlewu2508 可以做一次文献调研，哪些学者指出了 PMT 的 gain 服从 gamma 分布？

我记得最全面的 PMT gain 模型是 Polya 分布 (negative binomial 分布)，可以看作是 Gamma–Poisson mixture ，从而 gamma 分布看作是对 Polya 分布的近似。最好能找到文献让我们有个坚实的依据。
